# Generated by Django 6.0.2 on 2026-02-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('dayOpen', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dayHigh', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dayLow', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dayClose', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dayVolume', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
