# Generated by Django 6.0.2 on 2026-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dayClose',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayHigh',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayLow',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayOpen',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayVolume',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True),
        ),
    ]
