# Generated by Django 6.0.2 on 2026-02-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_stock_dayclose_alter_stock_dayhigh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dayVolume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
